### PR TITLE
Russian translation for Fourier transforms page

### PR DESCRIPTION
**Pull request by ye11owmonster**
Hi!
This is my translation of your great mateiral to Russian language!
It was even edited by professional :)
Please approve PR.

### CODE REVIEW

**Comment by ye11owmonster** [comment]
@Jezzamonn hello there, kind reminder:)

**Review by Jezzamonn — APPROVED** [review]
Great! I'll get these on the site soon!

**Comment by Jezzamonn** [comment]
And thanks for the reminder :)

**Comment by Jezzamonn** [comment]
Translation is live now! https://www.jezzamon.com/fourier/ru.html

**Pull request merged**
