### PR TITLE
Translating into Azerbaijani

### PR DESCRIPTION
**Pull request by absmj**

### CODE REVIEW

**Comment by absmj** [comment]
Hello Jezzamon. First of all, I would like to thank you for the article. It inspired me to search for new ideas. I have decided to translate the article into my native language (Azerbaijani). Please accept my pull request. Good luck with your work!

**Review by Jezzamonn — APPROVED** [review]

**Comment by Jezzamonn** [comment]
Hi! Sorry that I missed this earlier! This is awesome. I'll get this added now!

**Comment by Jezzamonn** [comment]
Translation is live now! https://www.jezzamon.com/fourier/az.html

**Comment by absmj** [comment]
> Translation is live now! https://www.jezzamon.com/fourier/az.html

Thanks 😊

**Pull request merged**
